# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

version_forge=36.1.25
version_minecraft=1.16.5
version_mcsupport=[1.16.5]
version_pcsupport=[3.11.5,)
version_mappings=1.16.5
channel_mappings=official

compile_name=pokeplayer
author_name=NelkGames, Thutmose
version_compile=3.0.0
