# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

version_forge=39.0.63
version_minecraft=1.18.1
version_mcsupport=[1.18,1.19)
version_pcsupport=[3.14.2,)
version_mappings=1.18.1
version_pokecube=285121:3623820
channel_mappings=official

mod_id=pokeplayer
compile_group=pokecube

compile_name=pokeplayer
author_name=NelkGames,Thutmose
version_compile=0.3.5